//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoMan.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOpeningStock
    {
        public int OpeningStockID { get; set; }
        public int ItemID { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        public virtual tblItem tblItem { get; set; }
    }
}
