//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoMan.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseProductDetail
    {
        public int PurchaseProductID { get; set; }
        public int PurchaseID { get; set; }
        public int ItemID { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblPurchase tblPurchase { get; set; }
    }
}
