//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoMan.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchase()
        {
            this.tblPurchaseProductDetails = new HashSet<tblPurchaseProductDetail>();
        }
    
        public int PurchaseID { get; set; }
        public int PurchaseNo { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal PurchaseAmount { get; set; }
        public string Narration { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseProductDetail> tblPurchaseProductDetails { get; set; }
    }
}
