//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoMan.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSale()
        {
            this.tblSaleProductDetails = new HashSet<tblSaleProductDetail>();
        }
    
        public int SaleID { get; set; }
        public int SaleNo { get; set; }
        public System.DateTime SaleDate { get; set; }
        public decimal SaleAmount { get; set; }
        public string Narration { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleProductDetail> tblSaleProductDetails { get; set; }
    }
}
